<?php

/**
 * @file
 * Uninstall function for the commerce_rbkmoney module.
 */

/**
 * Implements hook_uninstall().
 */
function commerce_rbkmoney_uninstall() {
  variable_del('commerce_rbkmoney_shop_id');
  variable_del('commerce_rbkmoney_merchant_private_key');
  variable_del('commerce_rbkmoney_merchant_callback_public_key');
  variable_del('commerce_rbkmoney_payform_path_logo');
  variable_del('commerce_rbkmoney_payform_button_label');
  variable_del('commerce_rbkmoney_payform_company_name');
  variable_del('commerce_rbkmoney_payform_description');
  variable_del('commerce_rbkmoney_log');
}
